### PR TITLE
Support updated_at and closed_at dates

### PR DESCRIPTION
**Pull request by zzzeek**
Github lets us set the date that the issue was closed as well
as an updated_at date.  Prevents seeing an issue with all
the comments from eight years ago and suddenly "user closed this
just now" :)  Still trying to see if they can do something similar for the labels.

### CODE REVIEW

**Comment by jeffwidman** [comment]
Thanks!

Is this info published somewhere? Or did you get it via official / informal support channels?

**Comment by zzzeek** [comment]
I think I saw them in the gist that appears to be the source of documentation for the whole thing :)

**Comment by zzzeek** [comment]
oh also yes I'm trying to get support to fix the issue where it says "zzzeek labeled this 'foobar' just now", because the labels should at least be changed no later than the "updated_at" date.   too much to ask for all the labels exactly when they occurred...

**Comment by jeffwidman** [comment]
> I think I saw them in the gist that appears to be the source of documentation for the whole thing :)

Gotcha, they must have updated it...

Well, if I can be of help, let me know, I've appreciated all the times you've answered my SQLAlchemy questions over the years, whether or not you remember, it's been at least 3-4 times you saved me hours of source spelunking.

**Comment by zzzeek** [comment]
I totally remember you which is why I'm being so casual :)

**Comment by zzzeek** [comment]
The github folks are hopefully going to improve the API a little bit and heck maybe even publish it , my plan is to start with less critical issue trackers like mako and dogpile, then get the whole infrastructure behind it going before pulling the switch on alembic and SQLAlchemy

**Comment by jeffwidman** [comment]
One other thing, the SQLAlchemy has non-contiguous issue IDs that will trigger this assert: https://github.com/jeffwidman/bitbucket-issue-migration/blob/master/migrate.py#L213-L221

Probably at some point in the past you used an issue tracker that allowed issues to be deleted. The way this script migrates issue cross-linking is by assuming the IDs are contiguous... that will break. 

Unfortunately, since this script migrates issues one at a time, the "aesthetically clean" fix of keeping track whenever a non-contiguous ID is hit and decrementing all the links won't work because of all the previous issues that might be linking to later issues.

So probably just need to make it so that it creates blank GH issues when this happens... note also that the script needs to look before it leaps by monitoring when BB returns non-contiguous IDs, because by the time it creates it in GH it's too late. If you're aware of any better solutions, I'm all ears.

**Comment by zzzeek** [comment]
Yeah you should create a blank issue.  When you read the bitbucket issues, you can look for gaps right up front and create blank issues.  Then you can delete them !  Eg use them just like they did on the BB side.

**Comment by jeffwidman** [comment]
> Then you can delete them !

Unfortunately, AFAIK Github doesn't let you delete issues. So the best we can do here is create them as empty and already closed.

This is still on my todo list, we just had a baby two weeks ago, so may be a little while as I'm kinda buried and sleep-deprived right now.

**Comment by zzzeek** [comment]
wow congratulations!   

no worries on TODO here, I have lots of contibutions already waiting for me and I'm out of my sqlalchemy window now.     I spoke to the github people and mentioned this issue so maybe they will come around with a solution.

**Pull request merged**
